### ISSUE TITLE
[AOS] feat: 거래/나눔 글 작성 API 연동

### ISSUE THREAD

**Issue by sey2** [DodamDuck/DodamDuck#103]
## ❄️ 주제 
> 거래/나눔 글 작성 API 연동

## 📝 Todo List
- [x] 거래/나눔 글 작성 API 연동 
- [x] 거래/나눔 작성 글 TextField 상태관리 
- [x] 갤러리에서 선택한 이미지 UI에 반영 
- [x] 앨버에서 가져온 사진 MultipartBody.Part로 변환
