### ISSUE TITLE
[AOS] feat: 거래/나눔 API 연동

### ISSUE THREAD

**Issue by sey2** [DodamDuck/DodamDuck#114]
## ❄️ 주제 
> 거래 / 나눔 상세보기 API 연동 후 UI에 반영

## 📝 Todo List
- [x] 거래 / 나눔 상세보기 API 연동 
- [x] 게시물 데이터 UI에 반영 
- [x] 댓글 데이터 UI에 반영 
- [x] 화면 상세보기에 스크롤 적용
