### ISSUE TITLE
[AOS] feat: 로그인 API 연동

### ISSUE THREAD

**Issue by sey2** [DodamDuck/DodamDuck#116]
## ❄️ 주제 
> 로그인 API 연동 후 UI 상태 반영

## 📝 Todo List
- [x] 로그인한 사용자 정보를 저장하는 클래스 선언
- [x] 로그인 API 연동 후 UI 반영 및 상태 관리
- [x] 로그인 API 연동
- [x] 비밀번호 *** 표시
- [x] 비밀번호 visibleIcon 변경
