### ISSUE TITLE
[FE] feat: 회원가입 API 연동

### ISSUE THREAD

**Issue by yunyoung0531** [DodamDuck/DodamDuck#120]
## ❄️ 주제 
> 회원가입 API 연동 후 UI 상태 반영 

## 📝 Todo List
- [x] 회원가입 API 연동
- [x] 회원가입 API 연동 후 UI 상태 반영 및 수정
- [x] 서버의 응답 구조에 따라 alert 구현
