### ISSUE TITLE
[FE] feat: 로그인 API 연동

### ISSUE THREAD

**Issue by yunyoung0531** [DodamDuck/DodamDuck#124]
## ❄️ 주제 
> 로그인 API 연동 후 UI 상태 반영

## 📝 Todo List
- [x] 로그인 API 연동
- [x] 로그인 API 연동 후 UI 반영
- [x] 서버 응답 구조에 따라 alert 구현 및 UI 수정
- [x] 로그인 상태 관리 React Context API
