### ISSUE TITLE
[AOS] feat: 글 상세보기 API 연동

### ISSUE THREAD

**Issue by sey2** [DodamDuck/DodamDuck#128]
## ❄️ 글 상세보기 API 연동
> 글 상세보기 API 연동 후 UI 상태 반영

## 📝 Todo List
- [x] 게시글 상세 보기 네비게이션 연동
- [x] 거래/나눔, 게시글 API 호출부 코드 리팩토
- [x] 게시글 -> 글 상세 보기 네비게이션 기능
