### ISSUE TITLE
[AOS] feat: 게시글 카테고리 API 연동

### ISSUE THREAD

**Issue by sey2** [DodamDuck/DodamDuck#136]
## ❄️ 주제 
> 카테고리 API 연동

## 📝 Todo List
- [x] 로그인 실패시 로그인이 안되는 버그 수정 
- [x] 게시글 카테고리 API 연동 후 UI 상태 반영
- [x] 게시글 Category API 연동
- [x] 게시글 이미지가 없을 때 보여줄 이미지 추가
