### ISSUE TITLE
[AOS] feat: 게시글 삭제 기능 및 게시물 상세보기 UI 추가 구현 

### ISSUE THREAD

**Issue by sey2** [DodamDuck/DodamDuck#144]
## ❄️ 주제 
> 게시글 삭제 기능 API 연동 UI 추가 구현

## 📝 Todo List
- [x] Screen, ViewModel을 분리하여 Preview가 동작 하도록 수정 
- [x] Modal Bottom Sheet 구현
- [x] 거래/나눔 삭제 API, 게시글 삭제 API 연동
