### ISSUE TITLE
[AOS] feat: 게시글 업로드, 삭제 API 연동

### ISSUE THREAD

**Issue by sey2** [DodamDuck/DodamDuck#154]
## ❄️ 주제 
> 게시글 업로드, 삭제 API 연동 

## 📝 Todo List
- [x] 게시글 업로드, 삭제 API 연동 
- [x] 게시글 작성, 이미지 불러오기
- [x] Screen, ViewModel 분리
- [x] 게시글 상세 화면 이미지 크기 조절 및 라운딩
- [x] TextField Custom Label 구현
- [x] Preview를 위한 Screen, ViewModel 분리
- [x] 게시글 작성 카테고리 바텀 시트 구현
- [x] 게시글 작성 api 호출 함수 분리
- [x] 게시글 작성 화면 - 갤러리에서 선택한 이미지 표시
