### ISSUE TITLE
[AOS] feat: 채팅 걸기 API 연동

### ISSUE THREAD

**Issue by sey2** [DodamDuck/DodamDuck#157]
## ❄️ 주제 
> 채팅 걸기 API 연동 및 게시글 삭제 API 수정 

## 📝 Todo List
- [x] 채팅 걸기 API 연동 
- [x] 게시글 삭제 API 연동
- [x] 날짜 -> 시간 변환 유틸 함수 구현
- [x] 채팅 리스트 UI 속성 변경
- [x] 채팅 걸기 UI 상태 반영
