### ISSUE TITLE
[AOS] fix: 자잘한 버그 수정 및 UI 수정

### ISSUE THREAD

**Issue by sey2** [DodamDuck/DodamDuck#164]
## ❄️ 주제 
> 자잘한 버그 수정 및 UI 수정 

## 📝 Todo List
- [x] navigation arg 추가 
- [x] 채팅 scroll 상태 관리
- [x] 댓글 작성시 scroll 상태 관리
- [x] 회원 가입 API 파라미터 변경
- [x] TextField외 다른 영역 터치 시 Focus 해제하는 함수 구현
- [x] 장난감 도서관 검색 기능 구현
- [x] 게시글 상세 화면에서 다른 화면 갔다 돌아왔을시 생기는 사이드 이펙트 해결
- [x] 하단 네비게이션 색상 변경
- [x] 채팅 리스트 상대 프로필 올바르게 표시 되지 않는 버그 수정
- [x] Navigation side effect 해결
