### ISSUE TITLE
[AOS] feat: 거래/나눔 검색 기능 구현

### ISSUE THREAD

**Issue by sey2** [DodamDuck/DodamDuck#173]
## ❄️ 주제 
> 검색 기능에 필요한 api 연동과 로컬 DB 구현 

## 📝 Todo List
- [x] 로컬 DB에서 검색 기록 가져와 UI 상태 반영
- [x] 로컬 DB 검색 기록 기능 구현
- [x] room 의존성 추가
- [x] 검색화면 네비게이션 연동
- [x] 거래/나눔 검색 기능 api 연동
- [x] 검색 기능 api 연동
