### ISSUE TITLE
[AOS] test: Compose UI 테스트 세팅, 온보딩 화면 네비게이션 테스트 코드 작성

### ISSUE THREAD

**Issue by sey2** [DodamDuck/DodamDuck#183]
## ❄️ Compose UI 테스트 세팅 및 온보딩 화면 네비게이션 테스트 코드 작성
> Compose UI 테스트 세팅 후 온보딩 화면 네비게이션 테스트 코드 작성한다.

## 📝 Todo List
- [x] Compose UI 테스트 세팅
- [x] 온보딩 화면 -> 로그인 화면 네비게이션 테스트 코드 작성
- [x] 온보딩 화면 -> 회원가입 화면 네비게이션 테스트 코드 작성
