### ISSUE TITLE
[AOS] refactor: Post, Trade, Detail MVI 적용

### ISSUE THREAD

**Issue by sey2** [DodamDuck/DodamDuck#200]
## ❄️ 주제 
> MVI 패턴 적용

## 📝 Todo List
- [x] 게시글 화면 MVI
- [x] 게시글 작성 MVI 적용
- [x] 거래 화면 MVI 적용
- [x] 거래 화면 작성 MVI 적용
- [x] 게시글, 거래 상세 화면 MVI 적용
