### ISSUE TITLE
[AOS] fix: 화면 전환 Flow 수정 

### ISSUE THREAD

**Issue by sey2** [DodamDuck/DodamDuck#216]
## ❄️ 주제 
> JetPack Navigation Stack에 대해 깊게 학습하고 BackStack 관리

## 📝 Todo List
- [x] 홈 화면 -> 로그인 화면 BackStack에 쌓이지 않게 수정하기
- [x] 전반적 화면 Flow를 확인해 Todo 작성
- [x] 거래/나눔 화면에서 두번 뒤로가기 버튼 클릭시 앱 종료 기능
