### ISSUE TITLE
[AOS] hotfix: 리팩토링 중 발생한 버그 수정

### ISSUE THREAD

**Issue by sey2** [DodamDuck/DodamDuck#218]
## ❄️ 주제 
> refactoring중 발생한 버그 수정 

## 📝 Todo List
- [x] 로그인 정보를 받아와 object 클래스에 저장하는 기능 다시 추가
- [x] 채팅방이 존재 할시 Toast 메세지 띄우기
- [x] 게시글 작성 오류 수정 
- [x] 게시글 작성시 이미지를 올리지 않으면 대체 이미지로 파일 전송
- [x] 게시글 작성 완료 후 거래/나눔 화면 또는 게시글 화면으로 이동하게 수정
- [x] 게시글 삭제 시 로그인 화면으로 이동하는 버그 수정
