### ISSUE TITLE
[BE]: JWT 토큰 기능 추가 

### ISSUE THREAD

**Issue by sey2** [DodamDuck/DodamDuck#223]
## ❄️ 주제 
> JWT 토큰 기능 추가하기 

## 📝 Todo List
- [x] JWT 토큰 기능 추가
- [x] JWT 기능을 추가하기 위한 환경 셋팅
- [x] 거래 / 나눔 전체 조회 검증 기능 추가
- [x] 거래 / 나눔 상세 조회 검증 기능 추가 
- [x] 거래 / 나눔 글 작성 검증 기능 추가
- [x] 거래 / 나눔 댓글 작성 검증 기능 추가
- [x] 거래 / 나눔 조회수 1 증가
- [x] 거래 / 나눔 삭제 검증 기능 추가
- [x] 사진 업로드 검증 기능 추가
- [x] 사진 조회 검증 기능 추가 
- [x] 게시글 전체 조회 검증 기능 추가
- [x] 게시글 상세 조회 검증 기능 추가
- [x] 게시글 댓글 작성 검증 기능 추가
- [x] 게시글 조회수 1 증가 검증 기능 추가
- [x] 게시글 작성 검증 기능 추가
- [x] 게시글 삭제 검증 기능 추가
- [x] 1:1 채팅 메세지 보내기 검증 기능 추가 
- [x] 1:1 채팅 내역 가져오기 검증 기능 추가
- [x] 1:1 채팅 걸기 검증 기능 추가 
- [x] 사용자 채팅 목록 가져오기 검증 기능 추가
- [x] 로그인 검증 기능 추가
- [x] 카테고리 전체 조회 검증 기능 추가
- [x] 검색하기 검증 기능 추가
- [x] 인기 검색어 검증 기능 추가
