### ISSUE TITLE
[AOS] design: AccessToken 여부에 따른 앱 시작점 변경

### ISSUE THREAD

**Issue by sey2** [DodamDuck/DodamDuck#234]
## ❄️ 주제 
> 글 작성시 오류 수정

## 📝 Todo List
- [x] 글 작성 후 거래/나눔 화면으로 이동 안하는 버그 수정하기
- [x] access token이 있을시 바로 Trade 화면으로 이동하게 수정
- [x] login 요청시 401 에러 해결
- [x] 로띠 화면 만들기
