### ISSUE TITLE
[AOS] design: 로그인 화면 개발 및 컴포넌트 리팩토링 

### ISSUE THREAD

**Issue by sey2** [DodamDuck/DodamDuck#33]
## ❄️ 로그인 화면 개발 및 리팩토링 
> 로그인 화면 UI를 개발하고 회원가입, 로그인 화면 공통 컴포넌트 리팩토링 진행

## 📝 Todo List
- [x] 로그인 화면 UI 개발 
- [x] 공통 컴포넌트 재사용성을 위한 리팩토링 
- [x] 로그인 <-> 회원가입 화면 전환 네비게이션 기능
