### ISSUE TITLE
[FE] design: 장난감 교환/나눔 화면 구현

### ISSUE THREAD

**Issue by yunyoung0531** [DodamDuck/DodamDuck#42]
## ❄️ 주제 
> 장난감 교환/나눔 화면 디자인

## 📝 Todo List
- [x] 연결 및 네브바 구현
- [x] 교환/나눔 화면 디자인
- [x] 글 등록 버튼 useNavigate 연결
- [x] 우선 리액트만으로 게시판 구현 방법 찾아보기
