### ISSUE TITLE
[AOS] feat: 장난감 도서관 api 호출 후 UI 반영

### ISSUE THREAD

**Issue by sey2** [DodamDuck/DodamDuck#53]
## ❄️ 주제 
> 의존성 주입 라이브러리 hilt와 http 통신을 위한 retrofit 설정 

## 📝 Todo List
- [x] liveData -> Flow 반영 
- [x] 코루틴을 이용한 비동기 처리
- [x] Text가 일정 길이를 넘어가면 ... 로 표시하는 기능
