### ISSUE TITLE
[FE] design: 게시판 UI 디자인

### ISSUE THREAD

**Issue by yunyoung0531** [DodamDuck/DodamDuck#57]
## ❄️ 주제 
> 도담덕 게시판 화면 디자인

## 📝 Todo List
- [x] 연결 및 네브바 구현
- [x] 전체적인 화면 디자인
- [x] 글 등록 버튼 useNavigate로 연결
