### ISSUE TITLE
[FE] design: 게시판 글 등록 UI

### ISSUE THREAD

**Issue by yunyoung0531** [DodamDuck/DodamDuck#58]
## ❄️ 주제 
> 도담덕 게시판 글 등록 화면 구현

## 📝 Todo List
- [x] 게시판 글 등록 화면 디자인
- [x] 이미지 등록 기능
- [x] 글 등록 기능
- [x] 게시판 UI에 보여주기
