### ISSUE TITLE
[AOS] desgin: 게시글 작성 화면 UI 

### ISSUE THREAD

**Issue by sey2** [DodamDuck/DodamDuck#66]
## ❄️ 게시글 작성 화면 UI 
> 게시글 작성화면 UI 개발 및 필요한 UI 컴포넌트 개발

## 📝 Todo List
- [x] 게시글 작성화면 UI 구성
- [x] 작성 완료 버튼 
- [x] InputText 컴포넌트 
- [x] 사진 썸네일 컴포넌트
