### ISSUE TITLE
[AOS] feat: Bottom Navigation 구현

### ISSUE THREAD

**Issue by sey2** [DodamDuck/DodamDuck#7]
## ❄️ 각 화면별 전환에 필요한 기능을 구현한다.
> 하단 네비게이션, 리소스 파일 추가, 각 화면 파일 구현

## 📝 Todo List
- [x] 하단 네비게이션 기능 구현
- [x] 네비게이션 아이콘 추가 
- [x] 하단 네비게이션 바 라운딩 및 쉐도우 효과
- [x] 리소스 파일 추가
- [x] 로그인, 회원가입, 홈, 장난감 도서관, 채팅, 게시판, 유저 화면 파일 생성
