### ISSUE TITLE
[AOS] desgin: 게시물 상세 화면 UI 구현

### ISSUE THREAD

**Issue by sey2** [DodamDuck/DodamDuck#78]
## ❄️ 게시물 상세 화면 UI 구현
> 게시물 상세 화면 UI 구현

## 📝 Todo List
- [x] UI 테스트를 위한 mock 데이터 코드 추가하기 
- [x] 사용자 댓글 리스트 UI 구현하기
- [x] 전체적인 게시물 상세 화면 UI 구현하기
