### ISSUE TITLE
[AOS] feat: 거래 / 나눔 API 연동

### ISSUE THREAD

**Issue by sey2** [DodamDuck/DodamDuck#97]
## ❄️ 거래/나눔 화면 API 연동 
> 거래/나눔 화면 API 연동 

## 📝 Todo List
- [x] Retrofit Builder 설정
- [x] TradeVideModel 구현
- [x] TradeApiService 구현
- [x] UI 상태 반영
- [x] 날짜 유틸 함수 구현
